Comprehension Check: Confusion Matrix
================

The following questions all ask you to work with the dataset described below.

The reported\_heights and heights datasets were collected from three classes taught in the Departments of Computer Science and Biostatistics, as well as remotely through the Extension School. The Biostatistics class was taught in 2016 along with an online version offered by the Extension School. On 2016-01-25 at 8:15 AM, during one of the lectures, the instructors asked student to fill in the sex and height questionnaire that populated the reported\_height dataset. The online students filled out the survey during the next few days, after the lecture was posted online. We can use this insight to define a variable which we will call type, to denote the type of student, inclass or online.

The code below sets up the dataset for you to analyze in the following exercises:

``` r
library(dslabs)
library(dplyr)
```

    ## 
    ## Attaching package: 'dplyr'

    ## The following objects are masked from 'package:stats':
    ## 
    ##     filter, lag

    ## The following objects are masked from 'package:base':
    ## 
    ##     intersect, setdiff, setequal, union

``` r
library(lubridate)
```

    ## 
    ## Attaching package: 'lubridate'

    ## The following object is masked from 'package:base':
    ## 
    ##     date

``` r
library(caret)
```

    ## Warning: package 'caret' was built under R version 3.5.3

    ## Loading required package: lattice

    ## Warning: package 'lattice' was built under R version 3.5.2

    ## Loading required package: ggplot2

``` r
library(purrr)
```

    ## 
    ## Attaching package: 'purrr'

    ## The following object is masked from 'package:caret':
    ## 
    ##     lift

``` r
data("reported_heights")

dat <- mutate(reported_heights, date_time = ymd_hms(time_stamp)) %>%
  filter(date_time >= make_date(2016, 01, 25) & date_time < make_date(2016, 02, 1)) %>%
  mutate(type = ifelse(day(date_time) == 25 & hour(date_time) == 8 & between(minute(date_time), 15, 30), "inclass","online")) %>%
  select(sex, type)

y <- factor(dat$sex, c("Female", "Male"))
x <- dat$type
```

Q1
--

The type column of dat indicates whether students took classes in person ("inclass") or online ("online"). What proportion of the inclass group is female? What proportion of the online group is female?

``` r
dat %>% 
  group_by(type) %>%
  summarize(Female = mean(sex == "Female"), Male = mean(sex == "Male"))
```

    ## # A tibble: 2 x 3
    ##   type    Female  Male
    ##   <chr>    <dbl> <dbl>
    ## 1 inclass  0.667 0.333
    ## 2 online   0.378 0.622

Q2
--

In the course videos, height cutoffs were used to predict sex. Instead of using height, use the type variable and report your prediction accuracy. Use what you learned about Q1 to make an informed guess about sex based on the most prevalent sex for each type. You do not need to split the data into training and test sets. Enter your answer as a percentage or decimal (eg "50%" or "0.50") to at least the hundredths place.

``` r
types <- dat %>% distinct(type)
accuracy <- map_dbl(types$type,function(x){
  y_hat <- ifelse(dat$type == x, "Female", "Male")
  mean(y_hat == dat$sex)
})  
```

**Answer : 0.633**

Q3
--

Write a line of code using the table function to show the confusion matrix between y\_hat and y. Use the format function(a, b) for your answer and do not name the columns and rows.

``` r
#table(y_hat, y)
y_hat <- ifelse(dat$type == "inclass", "Female", "Male")
table(y_hat, y)
```

    ##         y
    ## y_hat    Female Male
    ##   Female     26   13
    ##   Male       42   69

Q4
--

What is the sensitivity of this prediction? You can use the sensitivity function from the caret package. Enter your answer as a percentage or decimal (eg "50%" or "0.50") to at least the hundredths place.

``` r
types <- dat %>% distinct(type)
types_cutoff <- map_df(types$type, function(x){
  y_hat <- ifelse(dat$type == x, "Female", "Male") %>%
    factor(levels = c("Female", "Male"))
  list(method = "Type cutoff",
       FPR = specificity(y_hat,factor(dat$sex)),
       TPR = sensitivity(y_hat, factor(dat$sex)))
})

types_cutoff
```

    ## # A tibble: 2 x 3
    ##   method        FPR   TPR
    ##   <chr>       <dbl> <dbl>
    ## 1 Type cutoff 0.841 0.382
    ## 2 Type cutoff 0.159 0.618

Answer : 0.382

Q5
--

What is the specificity of this prediction? You can use the specificity function from the caret package. Enter your answer as a percentage or decimal (eg "50%" or "0.50") to at least the hundredths place.

From previouse question: 0.841

6
-

What is the prevalence (% of females) in the dat dataset defined above? Enter your answer as a percentage or decimal (eg "50%" or "0.50") to at least the hundredths place.

``` r
levels <- c("Female","Male")
confusionMatrix(data = factor(y_hat, levels = levels), reference = factor(dat$sex, levels = levels))
```

    ## Confusion Matrix and Statistics
    ## 
    ##           Reference
    ## Prediction Female Male
    ##     Female     26   13
    ##     Male       42   69
    ##                                           
    ##                Accuracy : 0.6333          
    ##                  95% CI : (0.5508, 0.7104)
    ##     No Information Rate : 0.5467          
    ##     P-Value [Acc > NIR] : 0.0195893       
    ##                                           
    ##                   Kappa : 0.2323          
    ##                                           
    ##  Mcnemar's Test P-Value : 0.0001597       
    ##                                           
    ##             Sensitivity : 0.3824          
    ##             Specificity : 0.8415          
    ##          Pos Pred Value : 0.6667          
    ##          Neg Pred Value : 0.6216          
    ##              Prevalence : 0.4533          
    ##          Detection Rate : 0.1733          
    ##    Detection Prevalence : 0.2600          
    ##       Balanced Accuracy : 0.6119          
    ##                                           
    ##        'Positive' Class : Female          
    ## 

Answer : 0.453
