Comprehension Check: Conditional Probabilities Review
================

Q1
--

In a previous module, we covered Bayes' theorem and the Bayesian paradigm. Conditional probabilities are a fundamental part of this previous covered rule.

![
P(A|B) = P(B|A)\\frac{P(A)}{P(B)}
](https://latex.codecogs.com/png.latex?%0AP%28A%7CB%29%20%3D%20P%28B%7CA%29%5Cfrac%7BP%28A%29%7D%7BP%28B%29%7D%0A "
P(A|B) = P(B|A)\frac{P(A)}{P(B)}
")

We first review a simple example to go over conditional probabilities.

Assume a patient comes into the doctor’s office to test whether they have a particular disease.

The test is positive 85% of the time when tested on a patient with the disease (high sensitivity): **P(test+|disease) = 0.85**
The test is negative 90% of the time when tested on a healthy patient (high specificity): **P(test-|heathy) = 0.90**
The disease is prevalent in about 2% of the community: **P(disease) = 0.02**
Using Bayes' theorem, calculate the probability that you have the disease if the test is positive.

![P(disease|test+)](https://latex.codecogs.com/png.latex?P%28disease%7Ctest%2B%29 "P(disease|test+)") = ![P(test+|disease) \\frac{P(disease)}{P(test+)}](https://latex.codecogs.com/png.latex?P%28test%2B%7Cdisease%29%20%5Cfrac%7BP%28disease%29%7D%7BP%28test%2B%29%7D "P(test+|disease) \frac{P(disease)}{P(test+)}") =

![
\\frac{P(test+)P(disease)}{P(test+|disease)P(disease) + P(test+|healthy)P(healthy)} =  
](https://latex.codecogs.com/png.latex?%0A%5Cfrac%7BP%28test%2B%29P%28disease%29%7D%7BP%28test%2B%7Cdisease%29P%28disease%29%20%2B%20P%28test%2B%7Chealthy%29P%28healthy%29%7D%20%3D%20%20%0A "
\frac{P(test+)P(disease)}{P(test+|disease)P(disease) + P(test+|healthy)P(healthy)} =  
")

``` r
(0.85 * 0.02)/((0.85 * 0.02) + (0.1 *0.98))
```

    ## [1] 0.1478261

**Result: ** 0.1478261

Problem description
===================

The following 4 questions (Q2-Q5) all relate to implementing this calculation using R.

We have a hypothetical population of 1 million individuals with the following conditional probabilities as described below:

The test is positive 85% of the time when tested on a patient with the disease (high sensitivity): **P(test+|disease) = 0.85**
The test is negative 90% of the time when tested on a healthy patient (high specificity): **P(test-|heathy) = 0.90**
The disease is prevalent in about 2% of the community: **P(disease) = 0.02**
Here is some sample code to get you started:

``` r
set.seed(1)
disease <- sample(c(0,1), size=1e6, replace=TRUE, prob=c(0.98,0.02))  
test <- rep(NA, 1e6)  
test[disease==0] <- sample(c(0,1), size=sum(disease==0), replace=TRUE, prob=c(0.90,0.10))  
test[disease==1] <- sample(c(0,1), size=sum(disease==1), replace=TRUE, prob=c(0.15, 0.85))  
```

Q2
--

**What is the probability that a test is positive?**

p(test+) = ?
True Positives plus False Positives

P(test+|disease)P(disease) + P(test+|health)P(health)

``` r
result <- (0.85 * 0.02) + (0.10 * 0.98)
result
```

    ## [1] 0.115

**Answer = 0.115**

Q3
--

**What is the probability that an individual has the disease if the test is negative?**

P(disease | test- ) = ?
P(test- | disease) \* P(disease) / P(test-)

p(test-) = P(test-| health) \* P(health) + P(test- | disease) P(disease)

``` r
result <-  (0.15) * (0.02)/ ( 0.90 * 0.98  + 0.15 * 0.02)
result
```

    ## [1] 0.003389831

**Answer: 0.0033**

Q4
--

What is the probability that you have the disease if the test is positive? Remember: calculate the conditional probability the disease is positive assuming a positive test.

P(test+| disease) P(disease) / P(test+)

``` r
result <- (0.85) * (0.02) / (0.115)
result
```

    ## [1] 0.1478261

**Answer: 0.1478261**

Q5
--

If the test is positive, what is the relative risk of having the disease?
First calculate the probability of having the disease given a positive test, then normalize it against the disease prevalence.

P(disease | test+ ) -&gt; P(test+ | disease) \* P(disease) / P(test+)

``` r
result <- mean(disease[test==1]==1)/mean(disease==1)
result
```

    ## [1] 7.389106

**Answer: 7.389106**
